### ISSUE TITLE
Specify redcapAppZip or REDCap community credentials as parameters

### ISSUE THREAD

**Issue by SvenAelterman** [kalalvishal/azure-redcap-paas#16]

**Comment by sjyang18** [comment]
@SvenAelterman 

I see this line for redcapAppZip in webapp.bicep.

var redcapUrl = 'https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.dropbox.com%2Fscl%2Ffi%2F4qag6pi0b2qstv67jzrbw%2Fredcap13.8.5.zip%3Frlkey%3Dhb0qjhqwnmhj9vvcc9akqhcpp%26dl%3D1&data=05%7C01%7Cvishalkalal%40microsoft.com%7Cb471a7309e7f484bde2508db9cd7079a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638276222972219379%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eqvY%2BTynSLyiiGdxAYTz5fMqJJrK6aNfg0SFbnbT4oU%3D&reserved=0'

Which is the the other credential you need to parameterize? I will take a look.
